### ISSUE TITLE
Shouldn't `async` be red all the time??

### ISSUE THREAD

**Issue by IamManchanda** [andrewmarkle/primer-light#2]
I love this theme btw :D 

<img width="600" alt="screen shot 2018-06-19 at 5 44 56 pm" src="https://user-images.githubusercontent.com/4970624/41596622-8e24a0c0-73e8-11e8-8f46-432062989ee9.png">

**Comment by andrewmarkle** [comment]
Hmm. Not sure why that's not working... It works for me when I type your code in.

<img width="460" alt="screen shot 2018-06-20 at 4 33 30 pm" src="https://user-images.githubusercontent.com/2506835/41683212-fa8e2370-74a7-11e8-9ae9-bcf20d92b9dc.png">

Which syntax are you using (I set mine to Javascript)?
